#synax: print(object,sep='character',end="charachter",file=sys.stdout,flush=False)

print('Print')
print()
print("Anamika")
print("Anamika",'Parul',"Pramod")
print(10)
print("Anamika "," Parul", sep ="**")
print(10,20,34, sep =",")
print("Anamika "," Parul", sep ="**",end=" Gupta")